"""create commits table

Revision ID: e5e311c2e5f0
Revises: 
Create Date: 2026-05-18 16:14:11.641995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5e311c2e5f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commits',
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('short_hash', sa.String(length=7), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('repo', sa.String(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commits')
    # ### end Alembic commands ###
